### ISSUE TITLE
Convert issue to epic in zenhub and change items in todo list to tasks

### ISSUE THREAD

**Issue by mortenwh** [metno/S-ENDA-project-plan#109]
See discussion for #96. 

- [x] Convert issue #96 to epic

- [x] Convert todo list items in#96 to tasks/issues under the epic

- [x] Add other tasks to #96, ref. comments in #96 

- [x] Estimate effort for each task in #96 (this will be reviewed at the backlog refinement meeting)

**Comment by TAlonglong** [comment]
Converting to epic

**Comment by TAlonglong** [comment]
OK, I think I got this to an EPIC

But I guess I have to create each point in #96 as a separate issue in this epic?

I Tried to import the #96 issue, but then its only listed as one issue I think.

**Comment by mortenwh** [comment]
OBS - you got it wrong. It was issue #96 that should be converted to epic... See updated description above :)

And hold on - we're learning along the way ;)
